name: Test pr branch delete action

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create pr branch
              id: pr-create
              run: |
                git config --global user.email "you@example.com"
                git config --global user.name "gcalacoci"
                git checkout -b pr-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
                touch test.txt
                git add test.txt
                git commit -m "Add test.txt"
                git push -f origin pr-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
                gh pr create --title "Pull request ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}" --body "Pull request body"
                echo "PR_NUMBER=$(gh pr list --state open --head pr-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} --json number --jq '.[].number')"
                echo "PR_NUMBER=$(gh pr list --state merged --head pr-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }} --json number --jq '.[].number')" >> "$GITHUB_OUTPUT"
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: print PR number
              env:
                PR_NUMBER: ${{ steps.pr-create.outputs.PR_NUMBER }}
              run: echo "$PR_NUMBER"
            - name: Remove PRs head branch
              uses: gcalacoci/action-delete-pr-branch@main
              env:
                PR_NUMBER: ${{ steps.pr-create.outputs.PR_NUMBER }}
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ env.PR_NUMBER }}
